name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action start
        uses: actions/checkout@v2

      - name: action-a
        uses: ./action-a
        with:
          MY_NAME: "Jack"